name: Exploring Variables and Secrets

on:
    push

jobs:
    docker: 
       runs-on: ubuntu-latest
       steps: 
       - name: TEMP Sleep command
         run: sleep 10

#   docker:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Docker Build
#       run: docker build -t docker.io/dockerUsername/imageName:latest
    
#     - name: Docker Login
#       run: docker login --username=dockerUsername --password=s3cUrePaSsw0rd

#     - name: Docker Publish
#       run: docker push docker.io/dockerUsername/imageName:latest
    
#    deploy:
#     needs: docker
#     runs-on: ubuntu-latest
#     steps:
#     - name: Docker Run
#       run: docker run -d -p 8080:80 docker.io/dockerUsername/imageName:latest
    
################# enviroment variables at STEP level###############################

#   docker:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Docker Build
#       env:
#         CONTAINER_REGISTRY: docker.io
#         DOCKER_USERNAME: siddharth1
#         IMAGE_NAME: github-actions-nginx
#       run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
    
#     - name: Docker Login
#       run: docker login --username=dockerUsername --password=s3cUrePaSsw0rd

#     - name: Docker Publish
#       run: docker push docker.io/dockerUsername/imageName:latest
    
#    deploy:
#     needs: docker
#     runs-on: ubuntu-latest
#     steps:
#     - name: Docker Run
#       run: docker run -d -p 8080:80 docker.io/dockerUsername/imageName:latest